#!/usr/bin/env python3
"""Audit Sentaurus/Vela current-density vector comparisons.

The input is the aligned node-field comparison CSV generated by
run_pn2d_coarse7x3_previous_full20_compare.py.  The audit intentionally works
from that neutral CSV so it can diagnose post-processing/export problems
without changing the coupled solve path.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[1]
DEFAULT_NODE_COMPARE = (
    REPO
    / "build-release/reference_tcad/pn2d_sentaurus2018_coarse7x3/reports"
    / "coarse_previous_full20_fields_20260629_155228/coarse_node_field_compare_aligned.csv"
)
DEFAULT_OUT_CSV = REPO / "build/diagnostics/current_density_vector_audit.csv"
DEFAULT_SUMMARY = REPO / "build/diagnostics/current_density_vector_audit_summary.md"
Q_C = 1.602176634e-19

VECTOR_PREFIXES = {
    "electric": "electric_field",
    "electron": "electron_current_density",
    "hole": "hole_current_density",
    "total": "total_current_density",
}

CURRENT_CARRIERS = ("electron", "hole", "total")

WINDOWS = {
    "full": (-math.inf, math.inf),
    "junction": (0.7, 1.3),
    "center": (0.9, 1.1),
    "left_shoulder": (0.7, 0.85),
    "right_shoulder": (1.15, 1.3),
}


def as_float(raw: str | None) -> float | None:
    if raw is None:
        return None
    text = str(raw).strip()
    if text == "":
        return None
    try:
        value = float(text)
    except ValueError:
        return None
    return value if math.isfinite(value) else None


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return [
            {str(key).strip(): str(value).strip() for key, value in row.items()}
            for row in csv.DictReader(handle, skipinitialspace=True)
        ]


def read_compare(path: Path) -> dict[tuple[float, int], dict[str, Any]]:
    nodes: dict[tuple[float, int], dict[str, Any]] = {}
    for row in read_csv_rows(path):
        bias = as_float(row.get("bias_V"))
        node_id_raw = row.get("node_id", "")
        quantity = row.get("quantity", "")
        if bias is None or node_id_raw == "" or quantity == "":
            continue
        node_id = int(float(node_id_raw))
        key = (bias, node_id)
        entry = nodes.setdefault(key, {
            "bias_V": bias,
            "node_id": node_id,
            "x_um": as_float(row.get("x_um")),
            "y_um": as_float(row.get("y_um")),
            "values": {},
        })
        entry["values"][quantity] = {
            "sent": as_float(row.get("sentaurus_value")),
            "self": as_float(row.get("vela_value_scaled_to_sentaurus_units")),
        }
    return nodes


def get_value(node: dict[str, Any], quantity: str, side: str) -> float | None:
    data = node["values"].get(quantity)
    if data is None:
        return None
    return data.get(side)


def vector_for(node: dict[str, Any], prefix: str, side: str) -> tuple[float, float, float] | None:
    x = get_value(node, f"{prefix}_x", side)
    y = get_value(node, f"{prefix}_y", side)
    mag = get_value(node, f"{prefix}_mag", side)
    if x is None or y is None or mag is None:
        return None
    return x, y, mag


def safe_ratio(numerator: float | None, denominator: float | None) -> float | None:
    if numerator is None or denominator is None or denominator == 0.0:
        return None
    return numerator / denominator


def median(values: list[float]) -> float | None:
    finite = sorted(v for v in values if math.isfinite(v))
    if not finite:
        return None
    mid = len(finite) // 2
    if len(finite) % 2:
        return finite[mid]
    return 0.5 * (finite[mid - 1] + finite[mid])


def mean(values: list[float]) -> float | None:
    finite = [v for v in values if math.isfinite(v)]
    if not finite:
        return None
    return sum(finite) / len(finite)


def rms(values: list[float]) -> float | None:
    finite = [v for v in values if math.isfinite(v)]
    if not finite:
        return None
    return math.sqrt(sum(v * v for v in finite) / len(finite))


def rel_error(candidate: float | None, reference: float | None) -> float | None:
    if candidate is None or reference is None:
        return None
    scale = max(abs(reference), 1.0e-300)
    return abs(candidate - reference) / scale


def window_name(x_um: float | None) -> str:
    if x_um is None:
        return "unknown"
    for name in ("left_shoulder", "center", "right_shoulder"):
        lo, hi = WINDOWS[name]
        if lo <= x_um <= hi:
            return name
    if WINDOWS["junction"][0] <= x_um <= WINDOWS["junction"][1]:
        return "junction_other"
    return "outside_junction"


def build_vector_node_rows(nodes: dict[tuple[float, int], dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for (_bias, _node_id), node in sorted(nodes.items()):
        for carrier, prefix in VECTOR_PREFIXES.items():
            sent = vector_for(node, prefix, "sent")
            self_value = vector_for(node, prefix, "self")
            if sent is None or self_value is None:
                continue
            sx, sy, smag = sent
            vx, vy, vmag = self_value
            sent_hypot = math.hypot(sx, sy)
            self_hypot = math.hypot(vx, vy)
            dot = sx * vx + sy * vy
            cosine = dot / (sent_hypot * self_hypot) if sent_hypot > 0.0 and self_hypot > 0.0 else None
            rows.append({
                "row_type": "vector_node",
                "bias_V": node["bias_V"],
                "node_id": node["node_id"],
                "x_um": node["x_um"],
                "y_um": node["y_um"],
                "window": window_name(node["x_um"]),
                "carrier": carrier,
                "sent_x": sx,
                "sent_y": sy,
                "sent_mag": smag,
                "self_x": vx,
                "self_y": vy,
                "self_mag": vmag,
                "sent_hypot_xy": sent_hypot,
                "self_hypot_xy": self_hypot,
                "sent_mag_consistency_abs": abs(sent_hypot - smag),
                "self_mag_consistency_abs": abs(self_hypot - vmag),
                "cosine_similarity": cosine,
                "ratio_x": safe_ratio(vx, sx),
                "ratio_y": safe_ratio(vy, sy),
                "ratio_mag": safe_ratio(vmag, smag),
                "component_error_norm": math.hypot(vx - sx, vy - sy),
                "component_error_norm_signflip": math.hypot(-vx - sx, -vy - sy),
                "high_signal_value": max(abs(smag), abs(vmag)),
            })
    return rows


def in_window(row: dict[str, Any], name: str) -> bool:
    x = row.get("x_um")
    if x is None:
        return False
    lo, hi = WINDOWS[name]
    return lo <= float(x) <= hi


def fit_scale(rows: list[dict[str, Any]]) -> float | None:
    numerator = 0.0
    denominator = 0.0
    for row in rows:
        vx = row.get("self_x")
        vy = row.get("self_y")
        sx = row.get("sent_x")
        sy = row.get("sent_y")
        if None in (vx, vy, sx, sy):
            continue
        numerator += float(vx) * float(sx) + float(vy) * float(sy)
        denominator += float(vx) * float(vx) + float(vy) * float(vy)
    return numerator / denominator if denominator > 0.0 else None


def build_vector_summary_rows(vector_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    groups: dict[tuple[float, str, str], list[dict[str, Any]]] = {}
    for row in vector_rows:
        for name in WINDOWS:
            if in_window(row, name):
                groups.setdefault((float(row["bias_V"]), str(row["carrier"]), name), []).append(row)
    for (bias, carrier, win), items in sorted(groups.items()):
        max_signal = max((float(item["high_signal_value"]) for item in items), default=0.0)
        threshold = max(max_signal * 1.0e-6, 1.0e-300)
        for sample_name, sample in [
            ("all", items),
            ("high_signal", [item for item in items if float(item["high_signal_value"]) >= threshold]),
        ]:
            if not sample:
                continue
            sign_err = [float(item["component_error_norm"]) for item in sample]
            flip_err = [float(item["component_error_norm_signflip"]) for item in sample]
            scale = fit_scale(sample)
            rows.append({
                "row_type": "vector_summary",
                "bias_V": bias,
                "carrier": carrier,
                "window": win,
                "sample": sample_name,
                "node_count": len(sample),
                "median_ratio_x": median([float(item["ratio_x"]) for item in sample if item.get("ratio_x") is not None]),
                "median_ratio_y": median([float(item["ratio_y"]) for item in sample if item.get("ratio_y") is not None]),
                "median_ratio_mag": median([float(item["ratio_mag"]) for item in sample if item.get("ratio_mag") is not None]),
                "max_mag_rel_error": max(
                    [rel_error(float(item["self_mag"]), float(item["sent_mag"])) or 0.0 for item in sample],
                    default=None,
                ),
                "median_cosine_similarity": median([
                    float(item["cosine_similarity"]) for item in sample if item.get("cosine_similarity") is not None
                ]),
                "rms_error_self_minus_sentaurus": rms(sign_err),
                "rms_error_neg_self_minus_sentaurus": rms(flip_err),
                "sign_flip_better": int((rms(flip_err) or math.inf) < (rms(sign_err) or math.inf)),
                "fit_scale_self_to_sentaurus": scale,
                "fit_scale_abs": None if scale is None else abs(scale),
                "median_sent_mag_consistency_abs": median([
                    float(item["sent_mag_consistency_abs"]) for item in sample
                ]),
                "median_self_mag_consistency_abs": median([
                    float(item["self_mag_consistency_abs"]) for item in sample
                ]),
            })
    return rows


def gava_rec(alpha_n: float | None, jn_mag: float | None, alpha_p: float | None, jp_mag: float | None, *, current_cm2: bool) -> float | None:
    if None in (alpha_n, jn_mag, alpha_p, jp_mag):
        return None
    value = (float(alpha_n) * abs(float(jn_mag)) + float(alpha_p) * abs(float(jp_mag))) / Q_C
    # Alpha is audited in m^-1.  If current is A/m^2, convert m^-3 s^-1 to cm^-3 s^-1.
    # If current is A/cm^2, first convert current density to A/m^2.
    return value * (1.0e-2 if current_cm2 else 1.0e-6)


def build_gava_rows(nodes: dict[tuple[float, int], dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for (_bias, _node_id), node in sorted(nodes.items()):
        for side in ("sent", "self"):
            alpha_n = get_value(node, "electron_alpha_avalanche", side)
            alpha_p = get_value(node, "hole_alpha_avalanche", side)
            jn = get_value(node, "electron_current_density_mag", side)
            jp = get_value(node, "hole_current_density_mag", side)
            exported = get_value(node, "avalanche", side)
            rec_m2 = gava_rec(alpha_n, jn, alpha_p, jp, current_cm2=False)
            rec_cm2 = gava_rec(alpha_n, jn, alpha_p, jp, current_cm2=True)
            if exported is None and rec_m2 is None and rec_cm2 is None:
                continue
            rows.append({
                "row_type": "gava_node",
                "bias_V": node["bias_V"],
                "node_id": node["node_id"],
                "x_um": node["x_um"],
                "y_um": node["y_um"],
                "window": window_name(node["x_um"]),
                "side": side,
                "alpha_n": alpha_n,
                "alpha_p": alpha_p,
                "jn_mag": jn,
                "jp_mag": jp,
                "gava_exported": exported,
                "gava_rec_A_per_m2_assumption": rec_m2,
                "gava_rec_A_per_cm2_assumption": rec_cm2,
                "gava_rec_rel_error_A_per_m2_assumption": rel_error(rec_m2, exported),
                "gava_rec_rel_error_A_per_cm2_assumption": rel_error(rec_cm2, exported),
            })
    return rows


def build_gava_summary_rows(gava_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    groups: dict[tuple[float, str, str], list[dict[str, Any]]] = {}
    for row in gava_rows:
        for name in WINDOWS:
            if in_window(row, name):
                groups.setdefault((float(row["bias_V"]), str(row["side"]), name), []).append(row)
    for (bias, side, win), items in sorted(groups.items()):
        result.append({
            "row_type": "gava_summary",
            "bias_V": bias,
            "side": side,
            "window": win,
            "node_count": len(items),
            "median_gava_rec_rel_error_A_per_m2_assumption": median([
                float(item["gava_rec_rel_error_A_per_m2_assumption"])
                for item in items
                if item.get("gava_rec_rel_error_A_per_m2_assumption") is not None
            ]),
            "median_gava_rec_rel_error_A_per_cm2_assumption": median([
                float(item["gava_rec_rel_error_A_per_cm2_assumption"])
                for item in items
                if item.get("gava_rec_rel_error_A_per_cm2_assumption") is not None
            ]),
            "median_gava_exported": median([
                float(item["gava_exported"]) for item in items if item.get("gava_exported") is not None
            ]),
            "median_gava_rec_A_per_m2_assumption": median([
                float(item["gava_rec_A_per_m2_assumption"])
                for item in items
                if item.get("gava_rec_A_per_m2_assumption") is not None
            ]),
        })
    return result


def read_elements_count(path: Path | None) -> int | None:
    if path is None or not path.exists():
        return None
    return max(0, len(read_csv_rows(path)))


def contact_closure_rows(
    nodes: dict[tuple[float, int], dict[str, Any]],
    mesh_json: Path | None,
    terminal_csv: Path | None,
) -> list[dict[str, Any]]:
    if mesh_json is None or not mesh_json.exists():
        return [{
            "row_type": "contact_closure",
            "contact_status": "unavailable_no_mesh_json",
        }]
    data = json.loads(mesh_json.read_text(encoding="utf-8"))
    contacts = data.get("contacts", [])
    if not contacts:
        return [{"row_type": "contact_closure", "contact_status": "unavailable_no_contacts"}]
    if terminal_csv is None or not terminal_csv.exists():
        return [{"row_type": "contact_closure", "contact_status": "unavailable_no_terminal_current_csv"}]
    coords = {int(node["id"]): (float(node["x"]), float(node["y"])) for node in data.get("nodes", [])}
    terminal_by_bias = {
        float(row["bias_V"]): as_float(row.get("current_total_A_per_um") or row.get("current_total"))
        for row in read_csv_rows(terminal_csv)
        if as_float(row.get("bias_V")) is not None
    }
    result: list[dict[str, Any]] = []
    for contact in contacts:
        ids = [int(item) for item in contact.get("node_ids", []) if int(item) in coords]
        if len(ids) < 2:
            continue
        xs = [coords[i][0] for i in ids]
        normal = (-1.0, 0.0) if abs(min(xs) - min(c[0] for c in coords.values())) < 1.0e-12 else (1.0, 0.0)
        ids.sort(key=lambda item: (coords[item][1], coords[item][0]))
        for bias in sorted({key[0] for key in nodes}):
            integral_a_per_m = 0.0
            used_segments = 0
            for a, b in zip(ids, ids[1:]):
                node_a = nodes.get((bias, a))
                node_b = nodes.get((bias, b))
                if node_a is None or node_b is None:
                    continue
                va = vector_for(node_a, "total_current_density", "self")
                vb = vector_for(node_b, "total_current_density", "self")
                if va is None or vb is None:
                    continue
                ax, ay = coords[a]
                bx, by = coords[b]
                length_m = math.hypot(bx - ax, by - ay) * 1.0e-6
                avg_jn = 0.5 * ((va[0] + vb[0]) * normal[0] + (va[1] + vb[1]) * normal[1])
                integral_a_per_m += avg_jn * length_m
                used_segments += 1
            terminal = terminal_by_bias.get(bias)
            integral_a_per_um = integral_a_per_m * 1.0e-6
            result.append({
                "row_type": "contact_closure",
                "bias_V": bias,
                "contact": contact.get("name", ""),
                "contact_status": "approximate_node_line_integral",
                "contact_segments": used_segments,
                "integral_total_current_A_per_um": integral_a_per_um,
                "terminal_current_A_per_um": terminal,
                "closure_ratio": safe_ratio(integral_a_per_um, terminal),
            })
    return result or [{"row_type": "contact_closure", "contact_status": "unavailable_no_contact_segments"}]


def collect_fields(rows: list[dict[str, Any]]) -> list[str]:
    preferred = [
        "row_type", "bias_V", "carrier", "side", "window", "sample", "node_id", "x_um", "y_um",
        "sent_x", "sent_y", "sent_mag", "self_x", "self_y", "self_mag",
        "sent_hypot_xy", "self_hypot_xy", "sent_mag_consistency_abs", "self_mag_consistency_abs",
        "cosine_similarity", "ratio_x", "ratio_y", "ratio_mag", "median_ratio_x",
        "median_ratio_y", "median_ratio_mag", "max_mag_rel_error", "median_cosine_similarity",
        "rms_error_self_minus_sentaurus", "rms_error_neg_self_minus_sentaurus", "sign_flip_better",
        "fit_scale_self_to_sentaurus", "fit_scale_abs", "high_signal_value", "node_count",
        "alpha_n", "alpha_p", "jn_mag", "jp_mag", "gava_exported",
        "gava_rec_A_per_m2_assumption", "gava_rec_A_per_cm2_assumption",
        "gava_rec_rel_error_A_per_m2_assumption", "gava_rec_rel_error_A_per_cm2_assumption",
        "median_gava_rec_rel_error_A_per_m2_assumption",
        "median_gava_rec_rel_error_A_per_cm2_assumption",
        "median_gava_exported", "median_gava_rec_A_per_m2_assumption",
        "elements_count", "contact", "contact_status", "contact_segments",
        "integral_total_current_A_per_um", "terminal_current_A_per_um", "closure_ratio",
    ]
    seen = set(preferred)
    extra = sorted({key for row in rows for key in row if key not in seen})
    return preferred + extra


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = collect_fields(rows)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def full_high_signal_summaries(summary_rows: list[dict[str, Any]], carrier: str) -> list[dict[str, Any]]:
    return [
        row for row in summary_rows
        if row.get("row_type") == "vector_summary"
        and row.get("carrier") == carrier
        and row.get("window") == "full"
        and row.get("sample") == "high_signal"
    ]


def aggregate_vector_summary(summary_rows: list[dict[str, Any]], carrier: str) -> dict[str, Any]:
    items = full_high_signal_summaries(summary_rows, carrier)
    return {
        "carrier": carrier,
        "bias_count": len(items),
        "median_ratio_mag": median([
            float(row["median_ratio_mag"]) for row in items if row.get("median_ratio_mag") not in (None, "")
        ]),
        "max_mag_rel_error": max([
            float(row["max_mag_rel_error"]) for row in items if row.get("max_mag_rel_error") not in (None, "")
        ], default=None),
        "median_fit_scale": median([
            float(row["fit_scale_self_to_sentaurus"])
            for row in items
            if row.get("fit_scale_self_to_sentaurus") not in (None, "")
        ]),
        "median_abs_fit_scale": median([
            float(row["fit_scale_abs"]) for row in items if row.get("fit_scale_abs") not in (None, "")
        ]),
        "median_cosine": median([
            float(row["median_cosine_similarity"])
            for row in items
            if row.get("median_cosine_similarity") not in (None, "")
        ]),
        "sign_flip_bias_count": sum(int(float(row.get("sign_flip_better") or 0.0)) for row in items),
    }


def aggregate_gava_summary(summary_rows: list[dict[str, Any]], side: str) -> dict[str, Any]:
    items = [
        row for row in summary_rows
        if row.get("row_type") == "gava_summary"
        and row.get("side") == side
        and row.get("window") == "full"
    ]
    return {
        "side": side,
        "bias_count": len(items),
        "median_err_m2": median([
            float(row["median_gava_rec_rel_error_A_per_m2_assumption"])
            for row in items
            if row.get("median_gava_rec_rel_error_A_per_m2_assumption") not in (None, "")
        ]),
        "median_err_cm2": median([
            float(row["median_gava_rec_rel_error_A_per_cm2_assumption"])
            for row in items
            if row.get("median_gava_rec_rel_error_A_per_cm2_assumption") not in (None, "")
        ]),
    }


def write_summary(
    path: Path,
    *,
    rows: list[dict[str, Any]],
    element_count: int | None,
) -> None:
    vector_summaries = [row for row in rows if row.get("row_type") == "vector_summary"]
    gava_summaries = [row for row in rows if row.get("row_type") == "gava_summary"]
    contact_rows = [row for row in rows if row.get("row_type") == "contact_closure"]
    efield = aggregate_vector_summary(vector_summaries, "electric")
    efield_median = efield.get("median_ratio_mag")
    efield_max = efield.get("max_mag_rel_error")
    current_lines: list[str] = []
    worst_carrier = ""
    worst_score = -math.inf
    for carrier in CURRENT_CARRIERS:
        item = aggregate_vector_summary(vector_summaries, carrier)
        if not item.get("bias_count"):
            continue
        score = abs(math.log10(max(float(item.get("median_abs_fit_scale") or 1.0), 1.0e-300)))
        if score > worst_score:
            worst_score = score
            worst_carrier = carrier
        current_lines.append(
            f"| {carrier} | {item.get('median_ratio_mag')} | {item.get('median_fit_scale')} | "
            f"{item.get('median_cosine')} | {item.get('sign_flip_bias_count')}/{item.get('bias_count')} |"
        )
    self_gava = aggregate_gava_summary(gava_summaries, "self")
    sent_gava = aggregate_gava_summary(gava_summaries, "sent")
    self_gava_err_m2 = self_gava.get("median_err_m2")
    self_gava_err_cm2 = self_gava.get("median_err_cm2")
    sent_gava_err_m2 = sent_gava.get("median_err_m2")
    sent_gava_err_cm2 = sent_gava.get("median_err_cm2")
    def error_or_inf(value: Any) -> float:
        return math.inf if value is None else float(value)

    self_gava_closes = min(error_or_inf(self_gava_err_m2), error_or_inf(self_gava_err_cm2)) < 0.1
    sent_gava_closes = min(error_or_inf(sent_gava_err_m2), error_or_inf(sent_gava_err_cm2)) < 0.1
    contact_statuses = sorted({str(row.get("contact_status", "")) for row in contact_rows if row.get("contact_status")})
    lines = [
        "# Current Density Vector Audit",
        "",
        "## Answers",
        "",
        f"1. ElectricField vector is {'aligned' if efield_median is not None and abs(float(efield_median) - 1.0) < 0.05 else 'not fully aligned'}: median |E| ratio={efield_median}, max |E| relative error={efield_max}.",
        "2. CurrentDensity vector shows a unit/mapping scale problem when median |Jself|/|Jsentaurus| is far from 1 or fitted |s| is far from 1.",
        "3. CurrentDensity vector sign convention check compares RMS(Jself-Jsentaurus) against RMS(-Jself-Jsentaurus); nonzero sign-flip counts flag likely sign convention or orientation mismatches.",
        f"4. Largest full-domain current-density scale anomaly: `{worst_carrier or 'unavailable'}`.",
        f"5. self exported current density {'can' if self_gava_closes else 'cannot'} reconstruct self AvalancheGeneration: median relative error A/m^2={self_gava_err_m2}, A/cm^2={self_gava_err_cm2}.",
        f"6. Sentaurus exported current density {'can' if sent_gava_closes else 'cannot'} reconstruct Sentaurus AvalancheGeneration: median relative error A/m^2={sent_gava_err_m2}, A/cm^2={sent_gava_err_cm2}.",
        "7. If current density cannot close Gava, the next diagnostic should export edge/cell/box-face current rather than relying on node current.",
        "",
        "## Current Vector Summary",
        "",
        "| carrier | median |Jself|/|Jsent| | median fit scale s | median cosine | sign-flip better biases |",
        "| --- | ---: | ---: | ---: | ---: |",
        *current_lines,
        "",
        "## Inputs",
        "",
        f"- elements.csv rows: `{element_count}`",
        f"- contact closure status: `{contact_statuses}`",
        "",
        "## Notes",
        "",
        "- Gava reconstruction is reported for both A/m^2 and A/cm^2 current-density assumptions in the CSV.",
        "- The Markdown answers aggregate full-domain high-signal vector statistics across all audited bias points.",
        "- Contact current closure is approximate unless the input mesh provides explicit contact faces and normals.",
        "",
        "CurrentDensity vector sign convention and unit-scale rows are in the CSV as `vector_summary`.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--node-compare-csv", type=Path, default=DEFAULT_NODE_COMPARE)
    parser.add_argument("--elements-csv", type=Path, default=None)
    parser.add_argument("--mesh-json", type=Path, default=None)
    parser.add_argument("--terminal-csv", type=Path, default=None)
    parser.add_argument("--out-csv", type=Path, default=DEFAULT_OUT_CSV)
    parser.add_argument("--summary-md", type=Path, default=DEFAULT_SUMMARY)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    nodes = read_compare(args.node_compare_csv)
    element_count = read_elements_count(args.elements_csv)
    vector_rows = build_vector_node_rows(nodes)
    vector_summary = build_vector_summary_rows(vector_rows)
    gava_rows = build_gava_rows(nodes)
    gava_summary = build_gava_summary_rows(gava_rows)
    meta_rows = [{
        "row_type": "input_summary",
        "node_count": len(nodes),
        "elements_count": element_count,
    }]
    contact_rows = contact_closure_rows(nodes, args.mesh_json, args.terminal_csv)
    all_rows = meta_rows + vector_rows + vector_summary + gava_rows + gava_summary + contact_rows
    write_csv(args.out_csv, all_rows)
    write_summary(args.summary_md, rows=all_rows, element_count=element_count)
    print(json.dumps({
        "node_count": len(nodes),
        "rows": len(all_rows),
        "out_csv": str(args.out_csv),
        "summary_md": str(args.summary_md),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
