"""Generate F1/2 Chebyshev coefficients from its defining integral.

Requires the optional development dependencies numpy/scipy, never at runtime.
The energy=t*t substitution removes the square-root endpoint singularity.
SciPy QUADPACK quadrature and DCT-II are used only to generate this small table.
Validate production functions independently in test_carrier_statistics.cpp.
"""
from pathlib import Path
import math
import numpy as np
from scipy.integrate import quad
from scipy.fft import dct
from scipy.special import expit, zeta

BOUNDS = [-8., -4., 0., 4., 8., 16., 32., 64.]
ORDER = 32


def reference(eta, derivative=False):
    upper = math.sqrt(max(eta, 0.) + 70.)
    def f(t):
        occupation = expit(eta-t*t)
        return t*t*occupation*(expit(t*t-eta) if derivative else 1.)
    return 4/math.sqrt(math.pi)*quad(f, 0., upper, epsabs=1e-14,
                                    epsrel=3e-14, limit=200)[0]


def main():
    tables=[];worst=0.;worst_derivative=0.
    for lo,hi in zip(BOUNDS, BOUNDS[1:]):
        nodes=np.cos(np.pi*(np.arange(ORDER)+.5)/ORDER)
        values=np.array([reference((lo+hi)/2+(hi-lo)/2*t) for t in nodes])
        coeff=dct(values,type=2)/ORDER;coeff[0]/=2
        # Drop quadrature/DCT roundoff tails, not physically resolved terms.
        while len(coeff)>2 and abs(coeff[-1])<2e-16*max(abs(values)):
            coeff=coeff[:-1]
        tables.append(coeff)
        derivative=np.polynomial.chebyshev.chebder(coeff)*2/(hi-lo)
        for x in np.linspace(-1,1,201):
            eta=(lo+hi)/2+(hi-lo)/2*x
            worst=max(worst,abs(np.polynomial.chebyshev.chebval(x,coeff)/reference(eta)-1))
            worst_derivative=max(worst_derivative,abs(np.polynomial.chebyshev.chebval(x,derivative)/reference(eta,True)-1))
    assert worst<2e-12 and worst_derivative<2e-11,(worst,worst_derivative)
    path=Path(__file__).resolve().parents[1]/'src/physics/FermiHalfCoefficients.inc'
    lines=['// Generated by scripts/generate_fermi_half_coefficients.py.',
           '// Normalized F1/2; independent defining-integral reference, no fitted device data.',
           'constexpr Real FermiBounds[] = {'+', '.join(f'{x:.1f}' for x in BOUNDS)+'};']
    for i,c in enumerate(tables):
        lines.append(f'constexpr Real FermiCoefficients{i}[] = {{')
        lines.extend('    '+format(float(v),'.17g')+',' for v in c)
        lines.append('};')
    lines.append('constexpr std::span<const Real> FermiCoefficients[] = {')
    lines.extend(f'    FermiCoefficients{i},' for i in range(len(tables)))
    lines.append('};')
    # Sommerfeld expansion of normalized F1/2 / (4 eta^(3/2)/(3 sqrt(pi))).
    falling=1.;coeff=[1.]
    for k in range(1,7):
        falling=math.prod(.5-j for j in range(2*k-1))
        coeff.append(3*(1-2**(1-2*k))*float(zeta(2*k))*falling)
    lines.append('constexpr Real FermiSommerfeld[] = {'+', '.join(format(v,'.17g') for v in coeff)+'};')
    path.write_text('\n'.join(lines)+'\n',encoding='utf8')
    print('max relative value/derivative quadrature error:',worst,worst_derivative)
    print('coefficient counts:',[len(t) for t in tables])


if __name__=='__main__':
    main()
