# CMake generated Testfile for 
# Source directory: /mnt/d/code-repo/vela-tcad
# Build directory: /mnt/d/code-repo/vela-tcad/wsl-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_scaling_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_mesh_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_poisson_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_linear_solver_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_box_geometry_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_device_stability_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_newton_solver_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_mos_solver_crosscheck_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_mobility_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_recombination_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_line_search_backtrack_failure_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_dc_sweep_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_solution_validation_include-b12d07c.cmake")
include("/mnt/d/code-repo/vela-tcad/wsl-build/test_electric_field_diagnostics_include-b12d07c.cmake")
add_test([=[python_api]=] "/usr/bin/python3" "/mnt/d/code-repo/vela-tcad/tests/python/test_python_api.py")
set_tests_properties([=[python_api]=] PROPERTIES  ENVIRONMENT "PYTHONPATH=/mnt/d/code-repo/vela-tcad/wsl-build/python/;VELA_SOURCE_DIR=/mnt/d/code-repo/vela-tcad" _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;102;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[ascii_sources]=] "/usr/bin/cmake" "-DVELA_SOURCE_DIR=/mnt/d/code-repo/vela-tcad" "-P" "/mnt/d/code-repo/vela-tcad/cmake/CheckAscii.cmake")
set_tests_properties([=[ascii_sources]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;131;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[example_runner_newton]=] "/mnt/d/code-repo/vela-tcad/wsl-build/vela_example_runner" "--config" "/mnt/d/code-repo/vela-tcad/examples/pn_diode/newton_simulation.json")
set_tests_properties([=[example_runner_newton]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;136;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[poisson]=] "/mnt/d/code-repo/vela-tcad/wsl-build/test_poisson" "[poisson]")
set_tests_properties([=[poisson]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;203;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[dd]=] "/mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel" "[gummel]")
set_tests_properties([=[dd]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;209;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[device_stability]=] "/mnt/d/code-repo/vela-tcad/wsl-build/test_device_stability" "[device_stability]")
set_tests_properties([=[device_stability]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;212;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[mos_solver_crosscheck]=] "/mnt/d/code-repo/vela-tcad/wsl-build/test_mos_solver_crosscheck" "[mos_solver_crosscheck]")
set_tests_properties([=[mos_solver_crosscheck]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;215;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[dc_sweep]=] "/mnt/d/code-repo/vela-tcad/wsl-build/test_dc_sweep" "[dc_sweep]")
set_tests_properties([=[dc_sweep]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;221;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[electric_field_diagnostics]=] "/mnt/d/code-repo/vela-tcad/wsl-build/test_electric_field_diagnostics" "[electric_field]")
set_tests_properties([=[electric_field_diagnostics]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;224;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
add_test([=[regression]=] "/usr/bin/python3" "/mnt/d/code-repo/vela-tcad/scripts/run_regression.py" "--repo" "/mnt/d/code-repo/vela-tcad" "--runner" "/mnt/d/code-repo/vela-tcad/wsl-build/vela_example_runner" "--workdir" "/mnt/d/code-repo/vela-tcad/wsl-build/regression_output")
set_tests_properties([=[regression]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/code-repo/vela-tcad/CMakeLists.txt;226;add_test;/mnt/d/code-repo/vela-tcad/CMakeLists.txt;0;")
