add_test( [==[Caughey-Thomas mobility decreases as doping increases]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mobility [==[Caughey-Thomas mobility decreases as doping increases]==]  )
set_tests_properties( [==[Caughey-Thomas mobility decreases as doping increases]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JSON solver config selects mobility and recombination models]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mobility [==[JSON solver config selects mobility and recombination models]==]  )
set_tests_properties( [==[JSON solver config selects mobility and recombination models]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Gummel PN diode runs with configured mobility and recombination]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mobility [==[Gummel PN diode runs with configured mobility and recombination]==]  )
set_tests_properties( [==[Gummel PN diode runs with configured mobility and recombination]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Caughey-Thomas field mobility rolls off toward velocity saturation]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mobility [==[Caughey-Thomas field mobility rolls off toward velocity saturation]==]  )
set_tests_properties( [==[Caughey-Thomas field mobility rolls off toward velocity saturation]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Material temperature path updates intrinsic density and mobility]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mobility [==[Material temperature path updates intrinsic density and mobility]==]  )
set_tests_properties( [==[Material temperature path updates intrinsic density and mobility]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_mobility_TESTS [==[Caughey-Thomas mobility decreases as doping increases]==] [==[JSON solver config selects mobility and recombination models]==] [==[Gummel PN diode runs with configured mobility and recombination]==] [==[Caughey-Thomas field mobility rolls off toward velocity saturation]==] [==[Material temperature path updates intrinsic density and mobility]==])
