if(EXISTS "/mnt/d/code-repo/vela-tcad/wsl-build/test_recombination_tests-b12d07c.cmake")
  include("/mnt/d/code-repo/vela-tcad/wsl-build/test_recombination_tests-b12d07c.cmake")
else()
  add_test(test_recombination_NOT_BUILT-b12d07c test_recombination_NOT_BUILT-b12d07c)
endif()
