if(EXISTS "/mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization_tests-b12d07c.cmake")
  include("/mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization_tests-b12d07c.cmake")
else()
  add_test(test_impact_ionization_NOT_BUILT-b12d07c test_impact_ionization_NOT_BUILT-b12d07c)
endif()
