add_test( [==[Impact ionization none model is zero]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization [==[Impact ionization none model is zero]==]  )
set_tests_properties( [==[Impact ionization none model is zero]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Selberherr impact ionization grows with electric field]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization [==[Selberherr impact ionization grows with electric field]==]  )
set_tests_properties( [==[Selberherr impact ionization grows with electric field]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Gummel reverse bias BV regression runs with impact ionization]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization [==[Gummel reverse bias BV regression runs with impact ionization]==]  )
set_tests_properties( [==[Gummel reverse bias BV regression runs with impact ionization]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Coupled DD residual includes impact-ionization generation]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization [==[Coupled DD residual includes impact-ionization generation]==]  )
set_tests_properties( [==[Coupled DD residual includes impact-ionization generation]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Coupled DD analytic avalanche Jacobian matches carrier finite differences]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization [==[Coupled DD analytic avalanche Jacobian matches carrier finite differences]==]  )
set_tests_properties( [==[Coupled DD analytic avalanche Jacobian matches carrier finite differences]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JSON solver config selects impact ionization model]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_impact_ionization [==[JSON solver config selects impact ionization model]==]  )
set_tests_properties( [==[JSON solver config selects impact ionization model]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_impact_ionization_TESTS [==[Impact ionization none model is zero]==] [==[Selberherr impact ionization grows with electric field]==] [==[Gummel reverse bias BV regression runs with impact ionization]==] [==[Coupled DD residual includes impact-ionization generation]==] [==[Coupled DD analytic avalanche Jacobian matches carrier finite differences]==] [==[JSON solver config selects impact ionization model]==])
