add_test( [==[DeviceMesh: node and cell counts]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[DeviceMesh: node and cell counts]==]  )
set_tests_properties( [==[DeviceMesh: node and cell counts]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DeviceMesh: edge count for two triangles sharing a diagonal]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[DeviceMesh: edge count for two triangles sharing a diagonal]==]  )
set_tests_properties( [==[DeviceMesh: edge count for two triangles sharing a diagonal]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DeviceMesh: all edge lengths are positive]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[DeviceMesh: all edge lengths are positive]==]  )
set_tests_properties( [==[DeviceMesh: all edge lengths are positive]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DeviceMesh: axis-aligned edge lengths are 1.0]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[DeviceMesh: axis-aligned edge lengths are 1.0]==]  )
set_tests_properties( [==[DeviceMesh: axis-aligned edge lengths are 1.0]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DeviceMesh: region name and material]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[DeviceMesh: region name and material]==]  )
set_tests_properties( [==[DeviceMesh: region name and material]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DeviceMesh: getNode out of range throws]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[DeviceMesh: getNode out of range throws]==]  )
set_tests_properties( [==[DeviceMesh: getNode out of range throws]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[MaterialDatabase: Si properties]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[MaterialDatabase: Si properties]==]  )
set_tests_properties( [==[MaterialDatabase: Si properties]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[MaterialDatabase: SiO2 properties]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[MaterialDatabase: SiO2 properties]==]  )
set_tests_properties( [==[MaterialDatabase: SiO2 properties]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[MaterialDatabase: unknown material throws]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[MaterialDatabase: unknown material throws]==]  )
set_tests_properties( [==[MaterialDatabase: unknown material throws]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects non-contiguous ids]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects non-contiguous ids]==]  )
set_tests_properties( [==[JsonMeshReader rejects non-contiguous ids]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects triangles with missing nodes]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects triangles with missing nodes]==]  )
set_tests_properties( [==[JsonMeshReader rejects triangles with missing nodes]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects triangles with missing regions]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects triangles with missing regions]==]  )
set_tests_properties( [==[JsonMeshReader rejects triangles with missing regions]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects triangles with the wrong node count]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects triangles with the wrong node count]==]  )
set_tests_properties( [==[JsonMeshReader rejects triangles with the wrong node count]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects inconsistent region cell references]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects inconsistent region cell references]==]  )
set_tests_properties( [==[JsonMeshReader rejects inconsistent region cell references]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects contacts with missing references]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects contacts with missing references]==]  )
set_tests_properties( [==[JsonMeshReader rejects contacts with missing references]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects regions with missing cells]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects regions with missing cells]==]  )
set_tests_properties( [==[JsonMeshReader rejects regions with missing cells]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader rejects contacts with missing regions]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader rejects contacts with missing regions]==]  )
set_tests_properties( [==[JsonMeshReader rejects contacts with missing regions]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[JsonMeshReader reports JSON schema errors with filename]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_mesh [==[JsonMeshReader reports JSON schema errors with filename]==]  )
set_tests_properties( [==[JsonMeshReader reports JSON schema errors with filename]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_mesh_TESTS [==[DeviceMesh: node and cell counts]==] [==[DeviceMesh: edge count for two triangles sharing a diagonal]==] [==[DeviceMesh: all edge lengths are positive]==] [==[DeviceMesh: axis-aligned edge lengths are 1.0]==] [==[DeviceMesh: region name and material]==] [==[DeviceMesh: getNode out of range throws]==] [==[MaterialDatabase: Si properties]==] [==[MaterialDatabase: SiO2 properties]==] [==[MaterialDatabase: unknown material throws]==] [==[JsonMeshReader rejects non-contiguous ids]==] [==[JsonMeshReader rejects triangles with missing nodes]==] [==[JsonMeshReader rejects triangles with missing regions]==] [==[JsonMeshReader rejects triangles with the wrong node count]==] [==[JsonMeshReader rejects inconsistent region cell references]==] [==[JsonMeshReader rejects contacts with missing references]==] [==[JsonMeshReader rejects regions with missing cells]==] [==[JsonMeshReader rejects contacts with missing regions]==] [==[JsonMeshReader reports JSON schema errors with filename]==])
