add_test( [==[SRH recombination is near zero when n*p equals ni squared]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[SRH recombination is near zero when n*p equals ni squared]==]  )
set_tests_properties( [==[SRH recombination is near zero when n*p equals ni squared]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Auger recombination increases at high carrier concentration]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[Auger recombination increases at high carrier concentration]==]  )
set_tests_properties( [==[Auger recombination increases at high carrier concentration]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Total recombination is SRH plus Auger]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[Total recombination is SRH plus Auger]==]  )
set_tests_properties( [==[Total recombination is SRH plus Auger]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Default bandgap narrowing interface returns zero]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[Default bandgap narrowing interface returns zero]==]  )
set_tests_properties( [==[Default bandgap narrowing interface returns zero]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Slotboom bandgap narrowing grows effective intrinsic density]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[Slotboom bandgap narrowing grows effective intrinsic density]==]  )
set_tests_properties( [==[Slotboom bandgap narrowing grows effective intrinsic density]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Effective intrinsic density caps overflow]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[Effective intrinsic density caps overflow]==]  )
set_tests_properties( [==[Effective intrinsic density caps overflow]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Bandgap narrowing factory validates model names]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[Bandgap narrowing factory validates model names]==]  )
set_tests_properties( [==[Bandgap narrowing factory validates model names]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[CarrierStatistics intrinsic density uses temperature_K material path]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_recombination [==[CarrierStatistics intrinsic density uses temperature_K material path]==]  )
set_tests_properties( [==[CarrierStatistics intrinsic density uses temperature_K material path]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_recombination_TESTS [==[SRH recombination is near zero when n*p equals ni squared]==] [==[Auger recombination increases at high carrier concentration]==] [==[Total recombination is SRH plus Auger]==] [==[Default bandgap narrowing interface returns zero]==] [==[Slotboom bandgap narrowing grows effective intrinsic density]==] [==[Effective intrinsic density caps overflow]==] [==[Bandgap narrowing factory validates model names]==] [==[CarrierStatistics intrinsic density uses temperature_K material path]==])
