add_test( [==[BoxGeometryBuilder: equilateral triangle area is correct]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_box_geometry [==[BoxGeometryBuilder: equilateral triangle area is correct]==]  )
set_tests_properties( [==[BoxGeometryBuilder: equilateral triangle area is correct]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[BoxGeometryBuilder: square node volumes sum to total area]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_box_geometry [==[BoxGeometryBuilder: square node volumes sum to total area]==]  )
set_tests_properties( [==[BoxGeometryBuilder: square node volumes sum to total area]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[BoxGeometryBuilder: all edge couplings are non-negative]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_box_geometry [==[BoxGeometryBuilder: all edge couplings are non-negative]==]  )
set_tests_properties( [==[BoxGeometryBuilder: all edge couplings are non-negative]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[BoxGeometryBuilder: warnings are opt-in]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_box_geometry [==[BoxGeometryBuilder: warnings are opt-in]==]  )
set_tests_properties( [==[BoxGeometryBuilder: warnings are opt-in]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[BoxGeometryBuilder: obtuse triangle reports fallback and keeps couplings non-negative]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_box_geometry [==[BoxGeometryBuilder: obtuse triangle reports fallback and keeps couplings non-negative]==]  )
set_tests_properties( [==[BoxGeometryBuilder: obtuse triangle reports fallback and keeps couplings non-negative]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_box_geometry_TESTS [==[BoxGeometryBuilder: equilateral triangle area is correct]==] [==[BoxGeometryBuilder: square node volumes sum to total area]==] [==[BoxGeometryBuilder: all edge couplings are non-negative]==] [==[BoxGeometryBuilder: warnings are opt-in]==] [==[BoxGeometryBuilder: obtuse triangle reports fallback and keeps couplings non-negative]==])
