add_test( [==[Gummel high-doping PN diode remains stable at 1e24 m^-3]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping [==[Gummel high-doping PN diode remains stable at 1e24 m^-3]==]  )
set_tests_properties( [==[Gummel high-doping PN diode remains stable at 1e24 m^-3]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Gummel high-doping forward bias does not produce invalid state]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping [==[Gummel high-doping forward bias does not produce invalid state]==]  )
set_tests_properties( [==[Gummel high-doping forward bias does not produce invalid state]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Gummel high-doping contacts use Slotboom bandgap narrowing]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping [==[Gummel high-doping contacts use Slotboom bandgap narrowing]==]  )
set_tests_properties( [==[Gummel high-doping contacts use Slotboom bandgap narrowing]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Gummel high-doping asymmetric reverse bias does not diverge]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping [==[Gummel high-doping asymmetric reverse bias does not diverge]==]  )
set_tests_properties( [==[Gummel high-doping asymmetric reverse bias does not diverge]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_gummel_high_doping_TESTS [==[Gummel high-doping PN diode remains stable at 1e24 m^-3]==] [==[Gummel high-doping forward bias does not produce invalid state]==] [==[Gummel high-doping contacts use Slotboom bandgap narrowing]==] [==[Gummel high-doping asymmetric reverse bias does not diverge]==])
