add_test( [==[ScalingSystem: thermal voltage at 300 K]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_scaling [==[ScalingSystem: thermal voltage at 300 K]==]  )
set_tests_properties( [==[ScalingSystem: thermal voltage at 300 K]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[ScalingSystem: Debye length is positive]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_scaling [==[ScalingSystem: Debye length is positive]==]  )
set_tests_properties( [==[ScalingSystem: Debye length is positive]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[ScalingSystem: scale/unscale potential round-trip]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_scaling [==[ScalingSystem: scale/unscale potential round-trip]==]  )
set_tests_properties( [==[ScalingSystem: scale/unscale potential round-trip]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[ScalingSystem: scale/unscale concentration round-trip]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_scaling [==[ScalingSystem: scale/unscale concentration round-trip]==]  )
set_tests_properties( [==[ScalingSystem: scale/unscale concentration round-trip]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[ScalingSystem: J0 and R0 are positive]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_scaling [==[ScalingSystem: J0 and R0 are positive]==]  )
set_tests_properties( [==[ScalingSystem: J0 and R0 are positive]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[ScalingSystem: invalid inputs throw]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_scaling [==[ScalingSystem: invalid inputs throw]==]  )
set_tests_properties( [==[ScalingSystem: invalid inputs throw]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_scaling_TESTS [==[ScalingSystem: thermal voltage at 300 K]==] [==[ScalingSystem: Debye length is positive]==] [==[ScalingSystem: scale/unscale potential round-trip]==] [==[ScalingSystem: scale/unscale concentration round-trip]==] [==[ScalingSystem: J0 and R0 are positive]==] [==[ScalingSystem: invalid inputs throw]==])
