add_test( [==[DDSolution validation rejects negative carrier density]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_solution_validation [==[DDSolution validation rejects negative carrier density]==]  )
set_tests_properties( [==[DDSolution validation rejects negative carrier density]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DDSolution validation rejects NaN state entries]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_solution_validation [==[DDSolution validation rejects NaN state entries]==]  )
set_tests_properties( [==[DDSolution validation rejects NaN state entries]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DDSolution validation accepts legal tiny positive carriers]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_solution_validation [==[DDSolution validation accepts legal tiny positive carriers]==]  )
set_tests_properties( [==[DDSolution validation accepts legal tiny positive carriers]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DDSolution validation tolerates tiny negative carrier roundoff]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_solution_validation [==[DDSolution validation tolerates tiny negative carrier roundoff]==]  )
set_tests_properties( [==[DDSolution validation tolerates tiny negative carrier roundoff]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DDSolution validation rejects contact quasi-Fermi mismatch]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_solution_validation [==[DDSolution validation rejects contact quasi-Fermi mismatch]==]  )
set_tests_properties( [==[DDSolution validation rejects contact quasi-Fermi mismatch]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_solution_validation_TESTS [==[DDSolution validation rejects negative carrier density]==] [==[DDSolution validation rejects NaN state entries]==] [==[DDSolution validation accepts legal tiny positive carriers]==] [==[DDSolution validation tolerates tiny negative carrier roundoff]==] [==[DDSolution validation rejects contact quasi-Fermi mismatch]==])
