if(EXISTS "/mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping_tests-b12d07c.cmake")
  include("/mnt/d/code-repo/vela-tcad/wsl-build/test_gummel_high_doping_tests-b12d07c.cmake")
else()
  add_test(test_gummel_high_doping_NOT_BUILT-b12d07c test_gummel_high_doping_NOT_BUILT-b12d07c)
endif()
