add_test( [==[Bernoulli: B(0) approx 1]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli [==[Bernoulli: B(0) approx 1]==]  )
set_tests_properties( [==[Bernoulli: B(0) approx 1]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Bernoulli: tiny x uses Taylor]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli [==[Bernoulli: tiny x uses Taylor]==]  )
set_tests_properties( [==[Bernoulli: tiny x uses Taylor]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Bernoulli: B(x) - B(-x) = -x]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli [==[Bernoulli: B(x) - B(-x) = -x]==]  )
set_tests_properties( [==[Bernoulli: B(x) - B(-x) = -x]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Bernoulli: non-negative and finite for a range of inputs]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli [==[Bernoulli: non-negative and finite for a range of inputs]==]  )
set_tests_properties( [==[Bernoulli: non-negative and finite for a range of inputs]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Bernoulli: large positive x does not overflow or underflow]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli [==[Bernoulli: large positive x does not overflow or underflow]==]  )
set_tests_properties( [==[Bernoulli: large positive x does not overflow or underflow]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Bernoulli: large negative x does not overflow]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_bernoulli [==[Bernoulli: large negative x does not overflow]==]  )
set_tests_properties( [==[Bernoulli: large negative x does not overflow]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_bernoulli_TESTS [==[Bernoulli: B(0) approx 1]==] [==[Bernoulli: tiny x uses Taylor]==] [==[Bernoulli: B(x) - B(-x) = -x]==] [==[Bernoulli: non-negative and finite for a range of inputs]==] [==[Bernoulli: large positive x does not overflow or underflow]==] [==[Bernoulli: large negative x does not overflow]==])
