if(EXISTS "/mnt/d/code-repo/vela-tcad/wsl-build/test_electric_field_diagnostics_tests-b12d07c.cmake")
  include("/mnt/d/code-repo/vela-tcad/wsl-build/test_electric_field_diagnostics_tests-b12d07c.cmake")
else()
  add_test(test_electric_field_diagnostics_NOT_BUILT-b12d07c test_electric_field_diagnostics_NOT_BUILT-b12d07c)
endif()
