add_test( [==[SG electron flux: pure diffusion (dpsi=0)]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[SG electron flux: pure diffusion (dpsi=0)]==]  )
set_tests_properties( [==[SG electron flux: pure diffusion (dpsi=0)]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[SG hole flux: pure diffusion (dpsi=0)]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[SG hole flux: pure diffusion (dpsi=0)]==]  )
set_tests_properties( [==[SG hole flux: pure diffusion (dpsi=0)]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[SG electron flux: zero at equilibrium]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[SG electron flux: zero at equilibrium]==]  )
set_tests_properties( [==[SG electron flux: zero at equilibrium]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[SG fluxes: antisymmetry J_ji = -J_ij]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[SG fluxes: antisymmetry J_ji = -J_ij]==]  )
set_tests_properties( [==[SG fluxes: antisymmetry J_ji = -J_ij]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[SG fluxes: finite for large dpsi]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[SG fluxes: finite for large dpsi]==]  )
set_tests_properties( [==[SG fluxes: finite for large dpsi]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[SG continuity residuals match DDAssembler and CoupledDDAssembler]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[SG continuity residuals match DDAssembler and CoupledDDAssembler]==]  )
set_tests_properties( [==[SG continuity residuals match DDAssembler and CoupledDDAssembler]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[CoupledDDAssembler validates doping size before BGN construction]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[CoupledDDAssembler validates doping size before BGN construction]==]  )
set_tests_properties( [==[CoupledDDAssembler validates doping size before BGN construction]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[Slotboom BGN uses total impurity density for compensated nodes]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[Slotboom BGN uses total impurity density for compensated nodes]==]  )
set_tests_properties( [==[Slotboom BGN uses total impurity density for compensated nodes]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[CoupledDDAssembler BGN residuals match DDAssembler with nonuniform ni]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[CoupledDDAssembler BGN residuals match DDAssembler with nonuniform ni]==]  )
set_tests_properties( [==[CoupledDDAssembler BGN residuals match DDAssembler with nonuniform ni]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[DDAssembler cached geometry matches fresh reference assembly]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_sg_flux [==[DDAssembler cached geometry matches fresh reference assembly]==]  )
set_tests_properties( [==[DDAssembler cached geometry matches fresh reference assembly]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_sg_flux_TESTS [==[SG electron flux: pure diffusion (dpsi=0)]==] [==[SG hole flux: pure diffusion (dpsi=0)]==] [==[SG electron flux: zero at equilibrium]==] [==[SG fluxes: antisymmetry J_ji = -J_ij]==] [==[SG fluxes: finite for large dpsi]==] [==[SG continuity residuals match DDAssembler and CoupledDDAssembler]==] [==[CoupledDDAssembler validates doping size before BGN construction]==] [==[Slotboom BGN uses total impurity density for compensated nodes]==] [==[CoupledDDAssembler BGN residuals match DDAssembler with nonuniform ni]==] [==[DDAssembler cached geometry matches fresh reference assembly]==])
