add_test( [==[GummelSolver: equilibrium (0 V bias) does not crash]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: equilibrium (0 V bias) does not crash]==]  )
set_tests_properties( [==[GummelSolver: equilibrium (0 V bias) does not crash]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: n and p are strictly positive]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: n and p are strictly positive]==]  )
set_tests_properties( [==[GummelSolver: n and p are strictly positive]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: no NaN or Inf in any output vector]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: no NaN or Inf in any output vector]==]  )
set_tests_properties( [==[GummelSolver: no NaN or Inf in any output vector]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: VTK output is written successfully]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: VTK output is written successfully]==]  )
set_tests_properties( [==[GummelSolver: VTK output is written successfully]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: forward bias converges without crash]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: forward bias converges without crash]==]  )
set_tests_properties( [==[GummelSolver: forward bias converges without crash]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: abstol can terminate strongly damped high-doping updates]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: abstol can terminate strongly damped high-doping updates]==]  )
set_tests_properties( [==[GummelSolver: abstol can terminate strongly damped high-doping updates]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: configured temperature scales ohmic built-in potential]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: configured temperature scales ohmic built-in potential]==]  )
set_tests_properties( [==[GummelSolver: configured temperature scales ohmic built-in potential]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: high doping gradient reverse bias remains finite]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: high doping gradient reverse bias remains finite]==]  )
set_tests_properties( [==[GummelSolver: high doping gradient reverse bias remains finite]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[GummelSolver: multi-terminal contact biases are imposed]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_dd_gummel [==[GummelSolver: multi-terminal contact biases are imposed]==]  )
set_tests_properties( [==[GummelSolver: multi-terminal contact biases are imposed]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_dd_gummel_TESTS [==[GummelSolver: equilibrium (0 V bias) does not crash]==] [==[GummelSolver: n and p are strictly positive]==] [==[GummelSolver: no NaN or Inf in any output vector]==] [==[GummelSolver: VTK output is written successfully]==] [==[GummelSolver: forward bias converges without crash]==] [==[GummelSolver: abstol can terminate strongly damped high-doping updates]==] [==[GummelSolver: configured temperature scales ohmic built-in potential]==] [==[GummelSolver: high doping gradient reverse bias remains finite]==] [==[GummelSolver: multi-terminal contact biases are imposed]==])
