if(EXISTS "/mnt/d/code-repo/vela-tcad/wsl-build/test_newton_solver_tests-b12d07c.cmake")
  include("/mnt/d/code-repo/vela-tcad/wsl-build/test_newton_solver_tests-b12d07c.cmake")
else()
  add_test(test_newton_solver_NOT_BUILT-b12d07c test_newton_solver_NOT_BUILT-b12d07c)
endif()
