add_test( [==[LinearSolver reuses symbolic analysis for identical sparse pattern]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_linear_solver [==[LinearSolver reuses symbolic analysis for identical sparse pattern]==]  )
set_tests_properties( [==[LinearSolver reuses symbolic analysis for identical sparse pattern]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[LinearSolver re-analyzes when sparse pattern changes]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_linear_solver [==[LinearSolver re-analyzes when sparse pattern changes]==]  )
set_tests_properties( [==[LinearSolver re-analyzes when sparse pattern changes]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[LinearSolver rejects invalid dimensions]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_linear_solver [==[LinearSolver rejects invalid dimensions]==]  )
set_tests_properties( [==[LinearSolver rejects invalid dimensions]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
add_test( [==[LinearSolver accepts uncompressed input and reuses its compressed pattern]==] /mnt/d/code-repo/vela-tcad/wsl-build/test_linear_solver [==[LinearSolver accepts uncompressed input and reuses its compressed pattern]==]  )
set_tests_properties( [==[LinearSolver accepts uncompressed input and reuses its compressed pattern]==] PROPERTIES WORKING_DIRECTORY /mnt/d/code-repo/vela-tcad/wsl-build)
set( test_linear_solver_TESTS [==[LinearSolver reuses symbolic analysis for identical sparse pattern]==] [==[LinearSolver re-analyzes when sparse pattern changes]==] [==[LinearSolver rejects invalid dimensions]==] [==[LinearSolver accepts uncompressed input and reuses its compressed pattern]==])
